import { CheckCircle2, GripVertical, RotateCcw, SlidersHorizontal } from 'lucide-react';
import { useMemo, useState, type ReactNode } from 'react';
import { useTranslation } from 'react-i18next';
import type { AppLocale, Chapter, Course, Lesson } from '../../data/courseContent';

type Props = { course: Course; chapter: Chapter; lesson: Lesson };
type Copy = {
  reset: string; scenario: string; choose: string; choiceIntro: string; choices: string[]; correct: string; retry: string;
  slide: string; autonomy: string; human: string; agent: string; value: string; risk: string; review: string; sliderLow: string; sliderMid: string; sliderHigh: string;
  drag: string; dragIntro: string; buckets: string[]; cards: string[]; check: string; incomplete: string; correctSort: string; reviseSort: string;
  sequence: string; sequenceIntro: string; steps: string[]; sequenceCorrect: string; sequenceRetry: string;
  compare: string; quick: string; production: string; quickPrompt: string; productionPrompt: string; quickBody: string; productionBody: string; criteria: string[]; score: string;
};

const copies: Record<AppLocale, Copy> = {
  'zh-CN': {
    reset: '重置', scenario: '现场决策', choose: '点击 · 选择并解释', choiceIntro: '客户把截止日期提前一周。哪一步最能保住交付质量？',
    choices: ['先承诺完整范围，后面再想办法', '锁定 Baseline、权限和 Gate，交付可评测的最小切片', '多加几个 Agent，让它们互相检查'], correct: '判断成立：先保护证据链，再扩大能力。', retry: '这个选项会增加隐藏债务。请补上边界、证据和 Owner。',
    slide: '滑动 · 观察权衡', autonomy: 'Agent 自主度', human: '人工主导', agent: 'Agent 自主', value: '交付价值', risk: '失控风险', review: '人工复核', sliderLow: '控制很强，但价值有限；可逐步放开低风险、可逆动作。', sliderMid: '处于 Pilot 区间；先跑边界样本，再决定是否扩权。', sliderHigh: '风险增长快于收益；增加审批、预算、停止条件和 Rollback。',
    drag: '拖拽 · 划分责任边界', dragIntro: '把卡片拖到正确区域；触控设备也可点击卡片循环移动。', buckets: ['Model 候选', '确定性控制', '人工授权'], cards: ['生成候选答案', '执行 ACL 检查', '批准高风险动作', 'API Retry 与幂等', '触发紧急停止', '记录 Audit Trace'], check: '检查边界', incomplete: '还有卡片未归类。', correctSort: '全部正确：概率能力、确定性控制和授权边界清楚。', reviseSort: '继续调整：ACL、Retry、停止与审计不能交给模型自由发挥。',
    sequence: '拖拽 · 重排交付 Gate', sequenceIntro: '拖动步骤，排出能阻止坏项目一路滑向 Production 的顺序。', steps: ['定义成功与 Baseline', '确认数据与权限', '构建最小 POC', '运行 Evaluation', '批准有限 Pilot', '验证 Handoff 与 Rollback'], sequenceCorrect: '顺序正确：每一步都用证据换取下一阶段。', sequenceRetry: '还可改进：先定义完成，再建系统；Production 前必须经过评测、Pilot 和交接。',
    compare: '对比 · 快速 Demo 与生产交付', quick: '方案 A · 快速 Demo', production: '方案 B · 生产流程', quickPrompt: '“做一个聪明的 Agent，周五展示。”', productionPrompt: '“先确认用户、Baseline、权限和 Gate；只交付可评测的最小切片。”', quickBody: '启动很快，但完成标准、风险和 Owner 都藏在期待里。', productionBody: '准备成本更高，却能处理失败、回滚和责任。', criteria: ['目标可判断', '权限有边界', '失败可恢复', '结果可追溯'], score: '已标记 {score}/4；勾选必须依据当前方案，而不是愿望。',
  },
  'zh-TW': {
    reset: '重設', scenario: '現場決策', choose: '點擊 · 選擇並解釋', choiceIntro: '客戶把 Deadline 提前一週。哪一步最能守住交付品質？',
    choices: ['先承諾完整 Scope，之後再想辦法', '鎖定 Baseline、權限與 Gate，交付可評測的最小切片', '多加幾個 Agent，期待它們互相檢查'], correct: '判斷成立：先保護證據鏈，再擴大能力。', retry: '這個選項會增加隱藏債務。請補上邊界、Evidence 與 Owner。',
    slide: '滑動 · 觀察取捨', autonomy: 'Agent 自主度', human: '人工主導', agent: 'Agent 自主', value: '交付價值', risk: '失控風險', review: '人工複核', sliderLow: '控制很強但價值有限；可逐步放開低風險、可逆動作。', sliderMid: '位於 Pilot 區間；先跑邊界案例，再決定是否擴權。', sliderHigh: '風險成長快於收益；增加審批、Budget、Stop Condition 與 Rollback。',
    drag: '拖曳 · 劃分責任邊界', dragIntro: '把卡片拖到正確區域；觸控裝置也可點擊卡片循環移動。', buckets: ['Model 候選', '確定性控制', '人工授權'], cards: ['生成候選答案', '執行 ACL 檢查', '批准高風險動作', 'API Retry 與 Idempotency', '觸發緊急停止', '記錄 Audit Trace'], check: '檢查邊界', incomplete: '仍有卡片尚未分類。', correctSort: '全部正確：機率能力、確定性控制與授權邊界清楚。', reviseSort: '繼續調整：ACL、Retry、停止與 Audit 不能交給 Model 自由發揮。',
    sequence: '拖曳 · 重排交付 Gate', sequenceIntro: '拖動步驟，排出能阻止壞專案一路滑向 Production 的順序。', steps: ['定義成功與 Baseline', '確認資料與權限', '建立最小 POC', '執行 Evaluation', '批准有限 Pilot', '驗證 Handoff 與 Rollback'], sequenceCorrect: '順序正確：每一步都用證據換取下一階段。', sequenceRetry: '還能改善：先定義完成，再建系統；Production 前要經過評測、Pilot 與交接。',
    compare: '比較 · 快速 Demo 與生產交付', quick: '方案 A · 快速 Demo', production: '方案 B · 生產流程', quickPrompt: '「做一個聰明 Agent，週五展示。」', productionPrompt: '「先確認使用者、Baseline、權限與 Gate；只交付可評測的最小切片。」', quickBody: '啟動很快，但完成標準、風險與 Owner 都藏在期待裡。', productionBody: '準備成本較高，卻能處理失敗、Rollback 與責任。', criteria: ['目標可判斷', '權限有邊界', '失敗可復原', '結果可追溯'], score: '已標記 {score}/4；勾選要根據目前方案，不是願望。',
  },
  en: {
    reset: 'Reset', scenario: 'Field decision', choose: 'CLICK · Choose and explain', choiceIntro: 'The customer moves the deadline forward by a week. Which action best protects delivery quality?',
    choices: ['Promise the complete scope now and solve the details later', 'Lock the baseline, permissions, and gate; then ship an evaluable thin slice', 'Add more agents so they can check one another'], correct: 'Sound judgment: protect the evidence chain before expanding capability.', retry: 'That choice creates hidden decision debt. Add a boundary, evidence, and an owner.',
    slide: 'SLIDE · Explore the trade-off', autonomy: 'Agent autonomy', human: 'Human-led', agent: 'Agent-led', value: 'Delivery value', risk: 'Loss-of-control risk', review: 'Human review', sliderLow: 'Control is strong, but value is limited. Open low-risk, reversible actions gradually.', sliderMid: 'This is pilot territory. Test boundary cases before expanding authority.', sliderHigh: 'Risk is rising faster than value. Add approval, budget, stop conditions, and rollback.',
    drag: 'DRAG · Assign responsibility', dragIntro: 'Drag each card into the right zone; touch and keyboard users can click to cycle it.', buckets: ['Model candidate', 'Deterministic control', 'Human authority'], cards: ['Generate a candidate answer', 'Enforce ACL checks', 'Approve a high-impact action', 'Retry APIs idempotently', 'Trigger an emergency stop', 'Record the audit trace'], check: 'Check boundaries', incomplete: 'Some cards are still unassigned.', correctSort: 'All correct: probabilistic capability, deterministic controls, and authority are separated.', reviseSort: 'Keep refining: ACL, retry, stop, and audit cannot be left to model discretion.',
    sequence: 'DRAG · Order the delivery gates', sequenceIntro: 'Reorder the gates so a weak project cannot slide straight into production.', steps: ['Define success and baseline', 'Confirm data and permissions', 'Build the smallest POC', 'Run evaluation', 'Approve a bounded pilot', 'Verify handoff and rollback'], sequenceCorrect: 'Correct: every stage earns the next one with evidence.', sequenceRetry: 'Not yet: define “done” before building, and require evaluation, pilot, and handoff before production.',
    compare: 'COMPARE · Fast demo vs production delivery', quick: 'Option A · Fast demo', production: 'Option B · Production path', quickPrompt: '“Build a smart agent for Friday’s demo.”', productionPrompt: '“Confirm the user, baseline, permissions, and gate; ship only an evaluable thin slice.”', quickBody: 'Fast to start, but success, risk, and ownership are hidden inside expectations.', productionBody: 'More preparation, but failure, rollback, and responsibility become operable.', criteria: ['Outcome is measurable', 'Permissions are bounded', 'Failure is recoverable', 'Results are traceable'], score: '{score}/4 marked. Score the current design, not the design you hope it becomes.',
  },
  fr: {
    reset: 'Réinitialiser', scenario: 'Décision terrain', choose: 'CLIQUER · Choisir et justifier', choiceIntro: 'Le client avance l’échéance d’une semaine. Quelle action protège le mieux la livraison ?',
    choices: ['Promettre tout le Scope et régler les détails plus tard', 'Verrouiller baseline, droits et Gate, puis livrer une tranche minimale évaluable', 'Ajouter des Agents afin qu’ils se contrôlent entre eux'], correct: 'Décision solide : protéger la chaîne de preuves avant d’étendre la capacité.', retry: 'Ce choix crée une dette cachée. Ajoutez une limite, une preuve et un Owner.',
    slide: 'GLISSER · Explorer le compromis', autonomy: 'Autonomie de l’Agent', human: 'Pilotage humain', agent: 'Agent autonome', value: 'Valeur livrée', risk: 'Risque de perte de contrôle', review: 'Revue humaine', sliderLow: 'Contrôle fort, valeur limitée : ouvrir progressivement les actions réversibles.', sliderMid: 'Zone de Pilot : tester les cas limites avant d’élargir l’autorité.', sliderHigh: 'Le risque croît plus vite que la valeur : ajouter approbation, budget, arrêt et rollback.',
    drag: 'GLISSER · Attribuer les responsabilités', dragIntro: 'Glissez chaque carte dans la bonne zone ; sur écran tactile, un clic la déplace.', buckets: ['Candidat du Model', 'Contrôle déterministe', 'Autorité humaine'], cards: ['Générer une réponse candidate', 'Appliquer les ACL', 'Approuver une action à fort impact', 'Rejouer une API avec idempotency', 'Déclencher l’arrêt d’urgence', 'Enregistrer l’Audit Trace'], check: 'Vérifier les limites', incomplete: 'Certaines cartes restent à classer.', correctSort: 'Tout est correct : capacité probabiliste, contrôles et autorité sont séparés.', reviseSort: 'À revoir : ACL, retry, arrêt et audit ne relèvent pas de la discrétion du Model.',
    sequence: 'GLISSER · Ordonner les Gates', sequenceIntro: 'Réordonnez les étapes pour empêcher un projet fragile d’arriver directement en Production.', steps: ['Définir réussite et baseline', 'Confirmer données et droits', 'Construire le plus petit POC', 'Exécuter l’Evaluation', 'Autoriser un Pilot borné', 'Vérifier Handoff et rollback'], sequenceCorrect: 'Correct : chaque étape obtient la suivante grâce à une preuve.', sequenceRetry: 'À revoir : définir « terminé » avant de construire ; Evaluation, Pilot et Handoff précèdent la Production.',
    compare: 'COMPARER · Démo rapide ou livraison', quick: 'Option A · Démo rapide', production: 'Option B · Production', quickPrompt: '« Construisez un Agent intelligent pour vendredi. »', productionPrompt: '« Confirmez utilisateur, baseline, droits et Gate ; livrez une tranche minimale évaluable. »', quickBody: 'Démarrage rapide, mais succès, risque et Owner restent implicites.', productionBody: 'Plus de préparation, mais échec, rollback et responsabilité deviennent exploitables.', criteria: ['Résultat mesurable', 'Droits bornés', 'Échec récupérable', 'Résultat traçable'], score: '{score}/4 cochés. Évaluez le design présent, pas celui espéré.',
  },
  es: {
    reset: 'Reiniciar', scenario: 'Decisión de campo', choose: 'PULSAR · Elegir y justificar', choiceIntro: 'El cliente adelanta una semana la fecha. ¿Qué acción protege mejor la entrega?',
    choices: ['Prometer todo el Scope y resolver los detalles después', 'Fijar baseline, permisos y Gate; entregar una porción mínima evaluable', 'Añadir más Agents para que se revisen entre sí'], correct: 'Buen criterio: proteger la cadena de evidencia antes de ampliar capacidad.', retry: 'Esa opción crea deuda oculta. Añade un límite, evidencia y un Owner.',
    slide: 'DESLIZAR · Explorar el equilibrio', autonomy: 'Autonomía del Agent', human: 'Control humano', agent: 'Agent autónomo', value: 'Valor entregado', risk: 'Riesgo de descontrol', review: 'Revisión humana', sliderLow: 'Hay mucho control y poco valor; abre gradualmente acciones reversibles.', sliderMid: 'Zona de Pilot: prueba límites antes de ampliar autoridad.', sliderHigh: 'El riesgo crece más rápido que el valor; añade aprobación, presupuesto, parada y rollback.',
    drag: 'ARRASTRAR · Asignar responsabilidad', dragIntro: 'Arrastra cada tarjeta a su zona; en táctil puedes pulsar para moverla.', buckets: ['Candidato del Model', 'Control determinista', 'Autoridad humana'], cards: ['Generar respuesta candidata', 'Aplicar ACL', 'Aprobar acción de alto impacto', 'Reintentar API con idempotency', 'Activar parada de emergencia', 'Registrar Audit Trace'], check: 'Comprobar límites', incomplete: 'Quedan tarjetas sin clasificar.', correctSort: 'Todo correcto: capacidad probabilística, controles y autoridad están separados.', reviseSort: 'Revisa: ACL, retry, parada y auditoría no pueden quedar a criterio del Model.',
    sequence: 'ARRASTRAR · Ordenar los Gates', sequenceIntro: 'Ordena los pasos para impedir que un proyecto débil llegue directo a Production.', steps: ['Definir éxito y baseline', 'Confirmar datos y permisos', 'Construir el POC mínimo', 'Ejecutar Evaluation', 'Aprobar un Pilot limitado', 'Verificar Handoff y rollback'], sequenceCorrect: 'Correcto: cada etapa gana la siguiente con evidencia.', sequenceRetry: 'Aún no: define “terminado” antes de construir; Evaluation, Pilot y Handoff preceden a Production.',
    compare: 'COMPARAR · Demo rápida o entrega', quick: 'Opción A · Demo rápida', production: 'Opción B · Producción', quickPrompt: '«Crea un Agent inteligente para el viernes.»', productionPrompt: '«Confirma usuario, baseline, permisos y Gate; entrega solo una porción mínima evaluable.»', quickBody: 'Arranca rápido, pero éxito, riesgo y Owner quedan implícitos.', productionBody: 'Exige preparación, pero fallo, rollback y responsabilidad se vuelven operables.', criteria: ['Resultado medible', 'Permisos limitados', 'Fallo recuperable', 'Resultado trazable'], score: '{score}/4 marcados. Evalúa el diseño actual, no el deseado.',
  },
};

function Shell({ title, eyebrow, copy, children, onReset }: { title: string; eyebrow: string; copy: Copy; children: ReactNode; onReset: () => void }) {
  return <section className="relative my-10 overflow-hidden rounded-[28px] border border-[#173b67]/20 bg-[#f7fbff] shadow-[0_22px_60px_rgba(23,59,103,0.12)]">
    <div className="absolute inset-x-0 top-0 h-1.5 bg-[linear-gradient(90deg,#174ea6_0_42%,#0f9f9a_42%_72%,#f16f55_72%)]" />
    <div className="flex items-start justify-between gap-4 border-b border-[#173b67]/15 px-5 py-5 sm:px-7"><div><p className="mb-1 text-[11px] font-bold uppercase tracking-[0.22em] text-[#c54f38]">{eyebrow}</p><h2 className="text-2xl font-black leading-tight text-[#173b67]">{title}</h2></div><button type="button" onClick={onReset} className="inline-flex shrink-0 items-center gap-1.5 rounded-full border border-[#173b67]/20 bg-white px-3 py-1.5 text-xs font-semibold text-[#173b67]"><RotateCcw className="h-3.5 w-3.5" />{copy.reset}</button></div>
    <div className="p-5 sm:p-7">{children}</div>
  </section>;
}

function ChoiceLab({ title, copy }: { title: string; copy: Copy }) {
  const [selected, setSelected] = useState<number | null>(null);
  return <Shell title={`${copy.scenario}: ${title}`} eyebrow={copy.choose} copy={copy} onReset={() => setSelected(null)}><p className="mb-5 text-sm leading-relaxed text-[#52657a]">{copy.choiceIntro}</p><div className="grid gap-3">{copy.choices.map((choice, index) => <button key={choice} type="button" onClick={() => setSelected(index)} className={`rounded-2xl border p-4 text-left text-sm leading-relaxed transition ${selected === index ? index === 1 ? 'border-emerald-600 bg-emerald-50 text-emerald-950' : 'border-[#d45d42] bg-[#fff1ed] text-[#6f2d1d]' : 'border-[#173b67]/15 bg-white text-[#263e59] hover:border-[#173b67]/45'}`}><span className="mr-3 inline-flex h-7 w-7 items-center justify-center rounded-full bg-[#174ea6] text-xs font-bold text-white">{String.fromCharCode(65 + index)}</span>{choice}</button>)}</div>{selected !== null && <p role="status" className={`mt-5 rounded-2xl p-4 text-sm font-semibold ${selected === 1 ? 'bg-emerald-100 text-emerald-950' : 'bg-[#fde4dc] text-[#6f2d1d]'}`}>{selected === 1 ? copy.correct : copy.retry}</p>}</Shell>;
}

function SliderLab({ title, copy }: { title: string; copy: Copy }) {
  const [autonomy, setAutonomy] = useState(45);
  const value = Math.round(35 + autonomy * 0.58); const risk = Math.round(10 + Math.pow(autonomy / 100, 1.7) * 86); const review = Math.round(94 - autonomy * 0.64);
  const message = autonomy < 30 ? copy.sliderLow : autonomy > 72 ? copy.sliderHigh : copy.sliderMid;
  return <Shell title={`${copy.autonomy}: ${title}`} eyebrow={copy.slide} copy={copy} onReset={() => setAutonomy(45)}><div className="rounded-2xl border border-[#173b67]/15 bg-white p-5"><div className="mb-3 flex items-end justify-between"><label htmlFor="fde-autonomy" className="text-sm font-bold text-[#173b67]">{copy.autonomy}</label><strong className="text-3xl text-[#d45d42]">{autonomy}%</strong></div><input id="fde-autonomy" type="range" min="0" max="100" value={autonomy} onChange={(event) => setAutonomy(Number(event.target.value))} className="h-2 w-full cursor-ew-resize accent-[#d45d42]" /><div className="mt-2 flex justify-between text-xs font-semibold text-[#68798b]"><span>{copy.human}</span><span>{copy.agent}</span></div></div><div className="mt-5 grid gap-3 sm:grid-cols-3">{[[copy.value, value, '#0f9f9a'], [copy.risk, risk, '#d45d42'], [copy.review, review, '#d19922']].map(([label, number, color]) => <div key={String(label)} className="rounded-2xl bg-[#173b67] p-4 text-white"><div className="flex justify-between text-xs text-white/75"><span>{label}</span><span>{number}%</span></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-white/15"><div className="h-full rounded-full transition-all" style={{ width: `${number}%`, backgroundColor: String(color) }} /></div></div>)}</div><p role="status" className="mt-5 flex gap-2 rounded-2xl bg-[#eaf2fb] p-4 text-sm text-[#334e68]"><SlidersHorizontal className="h-5 w-5 shrink-0 text-[#d45d42]" />{message}</p></Shell>;
}

function SortLab({ title, copy }: { title: string; copy: Copy }) {
  const expected = [0, 1, 2, 1, 1, 1];
  const [places, setPlaces] = useState<Array<number | null>>(copy.cards.map(() => null)); const [result, setResult] = useState('');
  const place = (index: number, bucket: number) => { setPlaces((current) => current.map((value, item) => item === index ? bucket : value)); setResult(''); };
  const reset = () => { setPlaces(copy.cards.map(() => null)); setResult(''); };
  const check = () => setResult(places.some((value) => value === null) ? copy.incomplete : places.every((value, index) => value === expected[index]) ? copy.correctSort : copy.reviseSort);
  return <Shell title={`${copy.drag}: ${title}`} eyebrow={copy.drag} copy={copy} onReset={reset}><p className="mb-4 text-sm text-[#52657a]">{copy.dragIntro}</p><div className="mb-5 flex min-h-16 flex-wrap gap-2 rounded-2xl border border-dashed border-[#173b67]/25 bg-white/60 p-3">{copy.cards.map((card, index) => places[index] === null && <button key={card} draggable onDragStart={(event) => event.dataTransfer.setData('text/plain', String(index))} onClick={() => place(index, 0)} className="inline-flex cursor-grab items-center gap-2 rounded-xl border border-[#173b67]/15 bg-white px-3 py-2 text-xs font-semibold text-[#263e59]"><GripVertical className="h-4 w-4 text-[#d45d42]" />{card}</button>)}</div><div className="grid gap-3 md:grid-cols-3">{copy.buckets.map((bucket, bucketIndex) => <div key={bucket} onDragOver={(event) => event.preventDefault()} onDrop={(event) => place(Number(event.dataTransfer.getData('text/plain')), bucketIndex)} className="min-h-36 rounded-2xl border border-[#173b67]/15 bg-[#eaf2fb] p-3"><h3 className="mb-3 text-center text-xs font-bold uppercase tracking-wide text-[#173b67]">{bucket}</h3><div className="space-y-2">{copy.cards.map((card, index) => places[index] === bucketIndex && <button key={card} draggable onDragStart={(event) => event.dataTransfer.setData('text/plain', String(index))} onClick={() => place(index, (bucketIndex + 1) % copy.buckets.length)} className="flex w-full cursor-grab items-center gap-2 rounded-xl bg-white px-3 py-2 text-left text-xs font-semibold text-[#263e59]"><GripVertical className="h-4 w-4 text-[#d45d42]" />{card}</button>)}</div></div>)}</div><div className="mt-5 flex flex-wrap items-center gap-3"><button type="button" onClick={check} className="rounded-full bg-[#174ea6] px-5 py-2.5 text-sm font-bold text-white">{copy.check}</button>{result && <p role="status" className="text-sm font-semibold text-[#52657a]">{result}</p>}</div></Shell>;
}

function SequenceLab({ title, copy }: { title: string; copy: Copy }) {
  const initial = [copy.steps[2], copy.steps[0], copy.steps[4], copy.steps[1], copy.steps[5], copy.steps[3]];
  const [steps, setSteps] = useState(initial); const [result, setResult] = useState('');
  const drop = (from: number, to: number) => { setSteps((current) => { const next = [...current]; const [item] = next.splice(from, 1); next.splice(to, 0, item); return next; }); setResult(''); };
  return <Shell title={`${copy.sequence}: ${title}`} eyebrow={copy.sequence} copy={copy} onReset={() => { setSteps(initial); setResult(''); }}><p className="mb-4 text-sm text-[#52657a]">{copy.sequenceIntro}</p><ol className="space-y-2">{steps.map((step, index) => <li key={step} draggable onDragStart={(event) => event.dataTransfer.setData('text/plain', String(index))} onDragOver={(event) => event.preventDefault()} onDrop={(event) => drop(Number(event.dataTransfer.getData('text/plain')), index)} className="flex cursor-grab items-center gap-3 rounded-2xl border border-[#173b67]/15 bg-white p-3"><GripVertical className="h-5 w-5 text-[#d45d42]" /><span className="inline-flex h-7 w-7 items-center justify-center rounded-full bg-[#174ea6] text-xs font-bold text-white">{index + 1}</span><span className="text-sm font-semibold text-[#263e59]">{step}</span></li>)}</ol><div className="mt-5 flex items-center gap-3"><button type="button" onClick={() => setResult(steps.every((step, index) => step === copy.steps[index]) ? copy.sequenceCorrect : copy.sequenceRetry)} className="rounded-full bg-[#174ea6] px-5 py-2.5 text-sm font-bold text-white">{copy.check}</button>{result && <p role="status" className="text-sm font-semibold text-[#52657a]">{result}</p>}</div></Shell>;
}

function CompareLab({ title, copy }: { title: string; copy: Copy }) {
  const [production, setProduction] = useState(false); const [checks, setChecks] = useState(copy.criteria.map(() => false)); const score = checks.filter(Boolean).length;
  return <Shell title={`${copy.compare}: ${title}`} eyebrow={copy.compare} copy={copy} onReset={() => { setProduction(false); setChecks(copy.criteria.map(() => false)); }}><div className="mb-5 grid grid-cols-2 rounded-full bg-[#dbe9f7] p-1 text-xs font-bold"><button type="button" onClick={() => setProduction(false)} className={`rounded-full px-4 py-2 ${!production ? 'bg-white text-[#d45d42] shadow-sm' : 'text-[#52657a]'}`}>{copy.quick}</button><button type="button" onClick={() => setProduction(true)} className={`rounded-full px-4 py-2 ${production ? 'bg-[#174ea6] text-white shadow-sm' : 'text-[#52657a]'}`}>{copy.production}</button></div><div className="rounded-2xl border border-[#173b67]/15 bg-white p-5"><p className="font-bold text-[#173b67]">{production ? copy.productionPrompt : copy.quickPrompt}</p><p className="mt-3 text-sm text-[#52657a]">{production ? copy.productionBody : copy.quickBody}</p></div><div className="mt-5 grid gap-2 sm:grid-cols-2">{copy.criteria.map((criterion, index) => <button key={criterion} type="button" onClick={() => setChecks((current) => current.map((value, item) => item === index ? !value : value))} className={`flex items-center gap-2 rounded-xl border px-3 py-3 text-sm font-semibold ${checks[index] ? 'border-emerald-500 bg-emerald-50 text-emerald-950' : 'border-[#173b67]/15 bg-white text-[#52657a]'}`}><CheckCircle2 className={`h-4 w-4 ${checks[index] ? 'text-emerald-600' : 'text-[#9aa9b7]'}`} />{criterion}</button>)}</div><p role="status" className="mt-5 rounded-2xl bg-[#173b67] p-4 text-sm text-white">{copy.score.replace('{score}', String(score))}</p></Shell>;
}

export function FdeInteractiveCourseware({ chapter, lesson }: Props) {
  const { i18n } = useTranslation();
  const locale = (i18n.resolvedLanguage ?? i18n.language) as AppLocale;
  const copy = copies[locale] ?? copies.en;
  const title = useMemo(() => `${chapter.chapter}.${lesson.lesson} ${lesson.title}`, [chapter.chapter, lesson.lesson, lesson.title]);
  if (lesson.interaction === 'slider') return <SliderLab title={title} copy={copy} />;
  if (lesson.interaction === 'sort') return <SortLab title={title} copy={copy} />;
  if (lesson.interaction === 'sequence') return <SequenceLab title={title} copy={copy} />;
  if (lesson.interaction === 'compare') return <CompareLab title={title} copy={copy} />;
  return <ChoiceLab title={title} copy={copy} />;
}
