import { ArrowDown, ArrowUp, CheckCircle2, GripVertical, RotateCcw, SlidersHorizontal, Sparkles } from 'lucide-react';
import React, { useMemo, useState } from 'react';
import { useTranslation } from 'react-i18next';
import type { AppLocale, Chapter, Course, Lesson } from '../../data/courseContent';

type Props = { course: Course; chapter: Chapter; lesson: Lesson };

type Copy = {
  reset: string;
  choiceEyebrow: string;
  choiceTitle: (scenario: string) => string;
  choicePrompt: string;
  choiceOptions: (concept: string) => string[];
  choiceCorrect: string;
  choiceWrong: string;
  sliderEyebrow: string;
  sliderTitle: (scenario: string) => string;
  autonomy: string;
  humanLed: string;
  aiLed: string;
  efficiency: string;
  risk: string;
  review: string;
  sliderLow: string;
  sliderMid: string;
  sliderHigh: string;
  sortEyebrow: string;
  sortTitle: (scenario: string) => string;
  sortPrompt: string;
  buckets: string[];
  cards: (scenario: string) => Array<{ id: string; label: string; expected: number }>;
  check: string;
  unplaced: (count: number) => string;
  sortCorrect: string;
  sortScore: (correct: number, total: number) => string;
  sequenceEyebrow: string;
  sequenceTitle: (scenario: string) => string;
  sequencePrompt: string;
  sequenceSteps: string[];
  sequenceCorrect: string;
  sequenceWrong: string;
  moveUp: (step: string) => string;
  moveDown: (step: string) => string;
  compareEyebrow: string;
  compareTitle: (scenario: string) => string;
  quick: string;
  production: string;
  quickPrompt: string;
  productionPrompt: (concepts: string[]) => string;
  quickBody: string;
  productionBody: string;
  criteriaPrompt: string;
  criteria: string[];
  compareScore: (score: number) => string;
};

const copies: Record<AppLocale, Copy> = {
  'zh-CN': {
    reset: '重置', choiceEyebrow: 'CLICK · 选择并解释', choiceTitle: (s) => `情境选择：${s}`,
    choicePrompt: '如果这项任务要交给真实同事继续维护，第一步应该怎么做？',
    choiceOptions: (c) => ['直接让 Codex 生成最终结果，看起来完整就采用', `先确认输入边界、${c} 与验收证据，再运行最小样本`, '把 Prompt 写得更长，但不改变事实来源和验证方式'],
    choiceCorrect: '判断成立：你先建立了可检查边界，再让 Codex 执行。', choiceWrong: '还不可靠：流畅输出或更长 Prompt 不能替代事实边界与验收标准。',
    sliderEyebrow: 'SLIDE · 拖动观察权衡', sliderTitle: (s) => `参数实验：为“${s}”设定自主度`, autonomy: '流程自主度', humanLed: '人工主导', aiLed: 'Codex 自主', efficiency: '交付效率', risk: '失控风险', review: '人工复核',
    sliderLow: '控制很强，但自动化收益有限；可逐步委托低风险、可逆步骤。', sliderMid: '处于试验区间；先用边界样本验证，再扩大范围。', sliderHigh: '自主度过高；请增加预算、停止条件和高风险人工审批。',
    sortEyebrow: 'DRAG · 拖拽或点击卡片', sortTitle: (s) => `责任分拣：${s}`, sortPrompt: '把每张卡片放到主要责任区域；触控或键盘用户可点击卡片轮换位置。', buckets: ['Codex 可执行', '需要人判断', '必须留证'],
    cards: (s) => [{ id: 'draft', label: `为“${s}”生成候选草稿`, expected: 0 }, { id: 'sample', label: '运行已授权的可逆小样本', expected: 0 }, { id: 'facts', label: '确认业务事实与验收标准', expected: 1 }, { id: 'approve', label: '批准高风险或外部动作', expected: 1 }, { id: 'trace', label: '记录输入、输出和环境', expected: 2 }, { id: 'verify', label: '检查测试、diff 或截图证据', expected: 2 }],
    check: '检查分工', unplaced: (n) => `还有 ${n} 张卡片未归类。`, sortCorrect: '全部正确：执行、判断和验证责任已经分开。', sortScore: (c, t) => `答对 ${c}/${t}；重新检查事实确认、高风险批准和证据复核。`,
    sequenceEyebrow: 'DRAG · 重排执行步骤', sequenceTitle: (s) => `流程排序：${s}`, sequencePrompt: '拖动卡片或使用上下按钮，排出一条可验证任务链。', sequenceSteps: ['定义验收标准', '整理可信输入', '运行最小样本', '人工复核', '记录并交接证据'], sequenceCorrect: '顺序正确：先定义完成，再准备输入、试跑、复核和留证。', sequenceWrong: '顺序仍可改进：生成前先定义验收和可信输入，最后保留复核证据。', moveUp: (s) => `上移 ${s}`, moveDown: (s) => `下移 ${s}`,
    compareEyebrow: 'COMPARE · 切换并检查', compareTitle: (s) => `方案对比：${s}`, quick: '方案 A · 快速生成', production: '方案 B · 生产流程', quickPrompt: '“请直接给出一份专业、详细、准确的最终结果。”', productionPrompt: (c) => `“先确认 ${c.join('、')} 与缺失信息；只使用已提供材料；输出逐项证据、unknown 和人工验收表。”`, quickBody: '启动快，但目标、事实边界和完成标准都藏在人的期待里，难以复现。', productionBody: '准备成本更高，但能区分事实与生成、显式处理缺失并进入可复核流程。', criteriaPrompt: '点击勾选当前方案真正满足的条件', criteria: ['目标可判断', '材料有边界', '失败有分支', '结果可追溯'], compareScore: (s) => `你标记了 ${s}/4 项。生产方案仍需真实样本验证，不能只凭模板判定可靠。`,
  },
  'zh-TW': {
    reset: '重設', choiceEyebrow: 'CLICK · 選擇並解釋', choiceTitle: (s) => `情境選擇：${s}`, choicePrompt: '若要把任務交給真實同事維護，第一步應該怎麼做？', choiceOptions: (c) => ['直接讓 Codex 產生最終結果，看起來完整就採用', `先確認輸入邊界、${c} 與驗收 evidence，再執行最小樣本`, '把 Prompt 寫得更長，但不改變事實來源與驗證'], choiceCorrect: '判斷成立：先建立可檢查邊界，再讓 Codex 執行。', choiceWrong: '仍不可靠：流暢輸出不能取代事實邊界與驗收。',
    sliderEyebrow: 'SLIDE · 拖動觀察權衡', sliderTitle: (s) => `參數實驗：為「${s}」設定自主度`, autonomy: '流程自主度', humanLed: '人工主導', aiLed: 'Codex 自主', efficiency: '交付效率', risk: '失控風險', review: '人工複核', sliderLow: '控制很強但自動化收益有限，可逐步委託可逆步驟。', sliderMid: '位於試驗區間，先用邊界樣本驗證。', sliderHigh: '自主度過高，請加入 budget、停止條件與人工審批。',
    sortEyebrow: 'DRAG · 拖曳或點擊卡片', sortTitle: (s) => `責任分揀：${s}`, sortPrompt: '把卡片放到主要責任區域；也可點擊輪換位置。', buckets: ['Codex 可執行', '需要人判斷', '必須留證'], cards: (s) => [{ id: 'draft', label: `為「${s}」產生候選草稿`, expected: 0 }, { id: 'sample', label: '執行已授權可逆樣本', expected: 0 }, { id: 'facts', label: '確認事實與驗收標準', expected: 1 }, { id: 'approve', label: '批准高風險動作', expected: 1 }, { id: 'trace', label: '記錄輸入、輸出與環境', expected: 2 }, { id: 'verify', label: '檢查 test、diff 或 screenshot', expected: 2 }], check: '檢查分工', unplaced: (n) => `還有 ${n} 張卡片未分類。`, sortCorrect: '全部正確：執行、判斷與驗證責任已分開。', sortScore: (c, t) => `答對 ${c}/${t}，請再檢查審批與 evidence。`,
    sequenceEyebrow: 'DRAG · 重排步驟', sequenceTitle: (s) => `流程排序：${s}`, sequencePrompt: '拖曳卡片或使用上下按鈕排出可驗證任務鏈。', sequenceSteps: ['定義驗收標準', '整理可信輸入', '執行最小樣本', '人工複核', '記錄並交接 evidence'], sequenceCorrect: '順序正確：先定義完成，再準備輸入、試跑、複核與留證。', sequenceWrong: '仍可改進：生成前先定義驗收與可信輸入。', moveUp: (s) => `上移 ${s}`, moveDown: (s) => `下移 ${s}`,
    compareEyebrow: 'COMPARE · 切換並檢查', compareTitle: (s) => `方案比較：${s}`, quick: '方案 A · 快速生成', production: '方案 B · Production flow', quickPrompt: '「請直接給出專業、詳細、準確的最終結果。」', productionPrompt: (c) => `「先確認 ${c.join('、')} 與缺失資訊；輸出 evidence、unknown 與人工驗收表。」`, quickBody: '啟動快，但事實邊界與完成標準都藏在期待裡。', productionBody: '準備成本較高，但能區分事實與生成並進入可複核流程。', criteriaPrompt: '勾選目前方案真正滿足的條件', criteria: ['目標可判斷', '材料有邊界', '失敗有分支', '結果可追溯'], compareScore: (s) => `你標記了 ${s}/4 項；仍需真實樣本驗證。`,
  },
  en: {
    reset: 'Reset', choiceEyebrow: 'CLICK · CHOOSE AND EXPLAIN', choiceTitle: (s) => `Scenario choice: ${s}`, choicePrompt: 'If a teammate must maintain this work, what should happen first?', choiceOptions: (c) => ['Ask Codex for the final answer and accept it if it looks complete', `Define input boundaries, ${c}, and acceptance evidence; then run a minimal sample`, 'Make the prompt longer without changing sources or verification'], choiceCorrect: 'Sound decision: you established an inspectable boundary before execution.', choiceWrong: 'Not reliable yet: fluency and prompt length cannot replace facts and acceptance evidence.',
    sliderEyebrow: 'SLIDE · OBSERVE THE TRADE-OFF', sliderTitle: (s) => `Autonomy experiment: ${s}`, autonomy: 'Workflow autonomy', humanLed: 'Human-led', aiLed: 'Codex-led', efficiency: 'Delivery efficiency', risk: 'Loss-of-control risk', review: 'Human review', sliderLow: 'Control is strong, but automation value is limited. Delegate low-risk reversible steps gradually.', sliderMid: 'This is an experimental range. Validate boundary cases before expanding scope.', sliderHigh: 'Autonomy is too high. Add budget, stop conditions, and approval for high-risk actions.',
    sortEyebrow: 'DRAG · SORT RESPONSIBILITIES', sortTitle: (s) => `Responsibility sort: ${s}`, sortPrompt: 'Place each card under its primary owner. Touch and keyboard users can click cards to rotate placement.', buckets: ['Codex may execute', 'Human judgment', 'Evidence required'], cards: (s) => [{ id: 'draft', label: `Draft a candidate result for “${s}”`, expected: 0 }, { id: 'sample', label: 'Run an authorized reversible sample', expected: 0 }, { id: 'facts', label: 'Confirm business facts and acceptance criteria', expected: 1 }, { id: 'approve', label: 'Approve high-risk or external actions', expected: 1 }, { id: 'trace', label: 'Record inputs, outputs, and environment', expected: 2 }, { id: 'verify', label: 'Review tests, diffs, or screenshot evidence', expected: 2 }], check: 'Check responsibilities', unplaced: (n) => `${n} cards are still unplaced.`, sortCorrect: 'All correct: execution, judgment, and verification now have distinct owners.', sortScore: (c, t) => `${c}/${t} correct. Revisit fact confirmation, high-risk approval, and evidence review.`,
    sequenceEyebrow: 'DRAG · ORDER THE WORKFLOW', sequenceTitle: (s) => `Workflow order: ${s}`, sequencePrompt: 'Drag cards or use the arrow buttons to create a verifiable task chain.', sequenceSteps: ['Define acceptance criteria', 'Prepare trusted inputs', 'Run a minimal sample', 'Perform human review', 'Record and hand off evidence'], sequenceCorrect: 'Correct: define done, prepare inputs, test, review, and preserve evidence.', sequenceWrong: 'Not yet: define acceptance and trusted input before generation, and retain review evidence last.', moveUp: (s) => `Move ${s} up`, moveDown: (s) => `Move ${s} down`,
    compareEyebrow: 'COMPARE · SWITCH AND CHECK', compareTitle: (s) => `Approach comparison: ${s}`, quick: 'Approach A · Quick generation', production: 'Approach B · Production workflow', quickPrompt: '“Produce a professional, detailed, and accurate final result now.”', productionPrompt: (c) => `“Confirm ${c.join(', ')} and missing information first; use only supplied material; return evidence, unknowns, and a human acceptance checklist.”`, quickBody: 'Fast to start, but goals, fact boundaries, and completion criteria remain hidden in human expectations.', productionBody: 'Higher setup cost, but facts and generation are separated, missing data is explicit, and review is reproducible.', criteriaPrompt: 'Select only the conditions the current approach truly satisfies', criteria: ['Goal is decidable', 'Inputs are bounded', 'Failure has a branch', 'Result is traceable'], compareScore: (s) => `You marked ${s}/4. A production workflow still needs validation on real samples.`,
  },
  fr: {
    reset: 'Réinitialiser', choiceEyebrow: 'CLIC · CHOISIR ET EXPLIQUER', choiceTitle: (s) => `Choix de scénario : ${s}`, choicePrompt: 'Si un collègue doit maintenir ce travail, quelle est la première étape ?', choiceOptions: (c) => ['Demander le résultat final à Codex et l’accepter s’il paraît complet', `Définir les entrées, ${c} et les preuves d’acceptation, puis tester un échantillon minimal`, 'Allonger le prompt sans changer les sources ni la vérification'], choiceCorrect: 'Décision solide : la limite est vérifiable avant exécution.', choiceWrong: 'Pas encore fiable : fluidité et longueur du prompt ne remplacent ni faits ni critères.',
    sliderEyebrow: 'CURSEUR · OBSERVER LE COMPROMIS', sliderTitle: (s) => `Expérience d’autonomie : ${s}`, autonomy: 'Autonomie du flux', humanLed: 'Pilotage humain', aiLed: 'Pilotage Codex', efficiency: 'Efficacité', risk: 'Risque de perte de contrôle', review: 'Revue humaine', sliderLow: 'Contrôle fort mais gain limité ; déléguez progressivement les étapes réversibles.', sliderMid: 'Zone expérimentale : validez les cas limites avant d’élargir.', sliderHigh: 'Autonomie excessive : ajoutez budget, conditions d’arrêt et approbation humaine.',
    sortEyebrow: 'GLISSER · RÉPARTIR LES RESPONSABILITÉS', sortTitle: (s) => `Répartition : ${s}`, sortPrompt: 'Placez chaque carte sous son responsable principal ; un clic fait tourner la position.', buckets: ['Codex peut exécuter', 'Décision humaine', 'Preuve obligatoire'], cards: (s) => [{ id: 'draft', label: `Produire un brouillon pour « ${s} »`, expected: 0 }, { id: 'sample', label: 'Exécuter un test réversible autorisé', expected: 0 }, { id: 'facts', label: 'Confirmer faits et critères d’acceptation', expected: 1 }, { id: 'approve', label: 'Approuver les actions à haut risque', expected: 1 }, { id: 'trace', label: 'Tracer entrées, sorties et environnement', expected: 2 }, { id: 'verify', label: 'Examiner tests, diff ou captures', expected: 2 }], check: 'Vérifier', unplaced: (n) => `${n} cartes restent à classer.`, sortCorrect: 'Correct : exécution, jugement et vérification sont séparés.', sortScore: (c, t) => `${c}/${t} correct. Revoyez validation des faits, approbation et preuves.`,
    sequenceEyebrow: 'GLISSER · ORDONNER LE FLUX', sequenceTitle: (s) => `Ordre du flux : ${s}`, sequencePrompt: 'Glissez les cartes ou utilisez les flèches pour créer une chaîne vérifiable.', sequenceSteps: ['Définir les critères d’acceptation', 'Préparer les entrées fiables', 'Exécuter un test minimal', 'Effectuer la revue humaine', 'Tracer et transmettre les preuves'], sequenceCorrect: 'Correct : définir, préparer, tester, revoir et conserver les preuves.', sequenceWrong: 'À revoir : définir l’acceptation et les entrées avant la génération.', moveUp: (s) => `Monter ${s}`, moveDown: (s) => `Descendre ${s}`,
    compareEyebrow: 'COMPARER · BASCULER ET VÉRIFIER', compareTitle: (s) => `Comparaison : ${s}`, quick: 'Option A · Génération rapide', production: 'Option B · Flux de production', quickPrompt: '« Produire immédiatement un résultat professionnel, détaillé et exact. »', productionPrompt: (c) => `« Confirmer ${c.join(', ')} et les informations manquantes ; fournir preuves, inconnues et checklist humaine. »`, quickBody: 'Démarrage rapide, mais objectifs, faits et critères restent implicites.', productionBody: 'Préparation plus longue, mais faits, manques et revue deviennent explicites.', criteriaPrompt: 'Cochez uniquement les conditions réellement satisfaites', criteria: ['Objectif décidable', 'Entrées bornées', 'Branche d’échec', 'Résultat traçable'], compareScore: (s) => `${s}/4 critères cochés. Le flux de production doit encore être testé sur des cas réels.`,
  },
  es: {
    reset: 'Restablecer', choiceEyebrow: 'CLIC · ELEGIR Y EXPLICAR', choiceTitle: (s) => `Elección de escenario: ${s}`, choicePrompt: 'Si otra persona debe mantener este trabajo, ¿qué debería ocurrir primero?', choiceOptions: (c) => ['Pedir a Codex el resultado final y aceptarlo si parece completo', `Definir límites de entrada, ${c} y evidencia de aceptación; después ejecutar una muestra mínima`, 'Alargar el prompt sin cambiar fuentes ni verificación'], choiceCorrect: 'Decisión sólida: primero estableciste un límite verificable.', choiceWrong: 'Aún no es fiable: fluidez y longitud no sustituyen hechos ni aceptación.',
    sliderEyebrow: 'SLIDER · OBSERVAR EL EQUILIBRIO', sliderTitle: (s) => `Experimento de autonomía: ${s}`, autonomy: 'Autonomía del flujo', humanLed: 'Dirigido por personas', aiLed: 'Dirigido por Codex', efficiency: 'Eficiencia', risk: 'Riesgo de descontrol', review: 'Revisión humana', sliderLow: 'Control fuerte y poco beneficio; delega gradualmente pasos reversibles.', sliderMid: 'Zona experimental: valida casos límite antes de ampliar.', sliderHigh: 'Autonomía excesiva: añade presupuesto, parada y aprobación humana.',
    sortEyebrow: 'ARRASTRAR · REPARTIR RESPONSABILIDADES', sortTitle: (s) => `Responsabilidades: ${s}`, sortPrompt: 'Coloca cada tarjeta bajo su responsable principal; también puedes hacer clic para rotarla.', buckets: ['Codex puede ejecutar', 'Decisión humana', 'Evidencia obligatoria'], cards: (s) => [{ id: 'draft', label: `Crear un borrador para «${s}»`, expected: 0 }, { id: 'sample', label: 'Ejecutar una muestra reversible autorizada', expected: 0 }, { id: 'facts', label: 'Confirmar hechos y aceptación', expected: 1 }, { id: 'approve', label: 'Aprobar acciones de alto riesgo', expected: 1 }, { id: 'trace', label: 'Registrar entradas, salidas y entorno', expected: 2 }, { id: 'verify', label: 'Revisar tests, diff o capturas', expected: 2 }], check: 'Comprobar', unplaced: (n) => `Quedan ${n} tarjetas sin clasificar.`, sortCorrect: 'Correcto: ejecución, juicio y verificación tienen responsables distintos.', sortScore: (c, t) => `${c}/${t} correctas. Revisa hechos, aprobación y evidencia.`,
    sequenceEyebrow: 'ARRASTRAR · ORDENAR EL FLUJO', sequenceTitle: (s) => `Orden del flujo: ${s}`, sequencePrompt: 'Arrastra las tarjetas o usa las flechas para crear una cadena verificable.', sequenceSteps: ['Definir criterios de aceptación', 'Preparar entradas fiables', 'Ejecutar una muestra mínima', 'Realizar revisión humana', 'Registrar y transferir evidencia'], sequenceCorrect: 'Correcto: definir, preparar, probar, revisar y conservar evidencia.', sequenceWrong: 'Aún no: define aceptación y entradas antes de generar.', moveUp: (s) => `Subir ${s}`, moveDown: (s) => `Bajar ${s}`,
    compareEyebrow: 'COMPARAR · CAMBIAR Y COMPROBAR', compareTitle: (s) => `Comparación: ${s}`, quick: 'Opción A · Generación rápida', production: 'Opción B · Flujo de producción', quickPrompt: '«Produce ahora un resultado profesional, detallado y exacto.»', productionPrompt: (c) => `«Confirma ${c.join(', ')} y la información ausente; devuelve evidencia, incógnitas y checklist humana.»`, quickBody: 'Arranca rápido, pero objetivo, límites y aceptación quedan implícitos.', productionBody: 'Requiere preparación, pero hace explícitos hechos, ausencias y revisión.', criteriaPrompt: 'Marca solo las condiciones que realmente cumple la opción', criteria: ['Objetivo decidible', 'Entradas delimitadas', 'Rama de fallo', 'Resultado trazable'], compareScore: (s) => `${s}/4 condiciones marcadas. El flujo de producción aún debe validarse con casos reales.`,
  },
};

function LabShell({ title, eyebrow, reset, children, onReset }: { title: string; eyebrow: string; reset: string; children: React.ReactNode; onReset?: () => void }) {
  return <section className="relative my-10 overflow-hidden rounded-[28px] border border-[#16324f]/20 bg-[#fbf8ee] shadow-[0_22px_60px_rgba(22,50,79,0.12)]"><div className="absolute inset-x-0 top-0 h-1.5 bg-[linear-gradient(90deg,#16324f_0_45%,#de5d3a_45%_72%,#e6b44a_72%)]" /><div className="border-b border-[#16324f]/15 px-5 py-5 sm:px-7"><div className="flex items-start justify-between gap-4"><div><p className="mb-1 text-[11px] font-bold uppercase tracking-[0.24em] text-[#de5d3a]">{eyebrow}</p><h2 className="text-[23px] font-bold leading-tight text-[#16324f]">{title}</h2></div>{onReset && <button type="button" onClick={onReset} className="inline-flex shrink-0 items-center gap-1.5 rounded-full border border-[#16324f]/20 bg-white/70 px-3 py-1.5 text-xs font-semibold text-[#16324f]"><RotateCcw className="h-3.5 w-3.5" />{reset}</button>}</div></div><div className="p-5 sm:p-7">{children}</div></section>;
}

function ChoiceLab({ scenario, concepts, copy }: { scenario: string; concepts: string[]; copy: Copy }) {
  const [selected, setSelected] = useState<number | null>(null); const options = copy.choiceOptions(concepts[0] ?? 'acceptance evidence');
  return <LabShell title={copy.choiceTitle(scenario)} eyebrow={copy.choiceEyebrow} reset={copy.reset} onReset={() => setSelected(null)}><p className="mb-5 text-sm leading-relaxed text-[#516170]">{copy.choicePrompt}</p><div className="grid gap-3">{options.map((option, index) => <button key={option} type="button" onClick={() => setSelected(index)} className={`rounded-2xl border p-4 text-left text-sm leading-relaxed ${selected === index ? index === 1 ? 'border-emerald-600 bg-emerald-50 text-emerald-950' : 'border-[#de5d3a] bg-[#fff1eb] text-[#6f2d1d]' : 'border-[#16324f]/15 bg-white/70 text-[#263b4f]'}`}><span className="mr-3 inline-flex h-7 w-7 items-center justify-center rounded-full bg-[#16324f] text-xs font-bold text-white">{String.fromCharCode(65 + index)}</span>{option}</button>)}</div>{selected !== null && <p role="status" className={`mt-5 rounded-2xl px-4 py-3 text-sm ${selected === 1 ? 'bg-emerald-100 text-emerald-950' : 'bg-[#fde4da] text-[#6f2d1d]'}`}>{selected === 1 ? copy.choiceCorrect : copy.choiceWrong}</p>}</LabShell>;
}

function SliderLab({ scenario, copy }: { scenario: string; copy: Copy }) {
  const [autonomy, setAutonomy] = useState(45); const efficiency = Math.round(38 + autonomy * 0.58), risk = Math.round(12 + Math.pow(autonomy / 100, 1.7) * 82), review = Math.round(92 - autonomy * 0.62); const recommendation = autonomy < 30 ? copy.sliderLow : autonomy > 72 ? copy.sliderHigh : copy.sliderMid;
  return <LabShell title={copy.sliderTitle(scenario)} eyebrow={copy.sliderEyebrow} reset={copy.reset} onReset={() => setAutonomy(45)}><div className="rounded-2xl border border-[#16324f]/15 bg-white/75 p-5"><div className="mb-3 flex items-end justify-between"><label htmlFor="autonomy-slider" className="text-sm font-bold text-[#16324f]">{copy.autonomy}</label><span className="text-3xl font-bold text-[#de5d3a]">{autonomy}%</span></div><input id="autonomy-slider" className="h-2 w-full accent-[#de5d3a]" type="range" min="0" max="100" value={autonomy} onChange={(event) => setAutonomy(Number(event.target.value))} /><div className="mt-2 flex justify-between text-[11px] font-semibold uppercase text-[#73808d]"><span>{copy.humanLed}</span><span>{copy.aiLed}</span></div></div><div className="mt-5 grid gap-3 sm:grid-cols-3">{[[copy.efficiency, efficiency, '#168a75'], [copy.risk, risk, '#de5d3a'], [copy.review, review, '#d39b24']].map(([label, value, color]) => <div key={String(label)} className="rounded-2xl bg-[#16324f] p-4 text-white"><div className="flex justify-between text-xs text-white/70"><span>{label}</span><span>{value}%</span></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-white/15"><div className="h-full rounded-full" style={{ width: `${value}%`, backgroundColor: String(color) }} /></div></div>)}</div><p role="status" className="mt-5 flex gap-2 rounded-2xl bg-[#efe8d5] p-4 text-sm text-[#35495d]"><SlidersHorizontal className="h-5 w-5 shrink-0 text-[#de5d3a]" />{recommendation}</p></LabShell>;
}

function SortLab({ scenario, copy }: { scenario: string; copy: Copy }) {
  const cards = useMemo(() => copy.cards(scenario), [copy, scenario]); const empty = () => Object.fromEntries(cards.map((card) => [card.id, null])) as Record<string, number | null>; const [placements, setPlacements] = useState<Record<string, number | null>>(empty); const [result, setResult] = useState(''); const place = (id: string, bucket: number) => { setPlacements((current) => ({ ...current, [id]: bucket })); setResult(''); }; const evaluate = () => { const placed = cards.filter((card) => placements[card.id] !== null); const correct = placed.filter((card) => placements[card.id] === card.expected).length; setResult(placed.length < cards.length ? copy.unplaced(cards.length - placed.length) : correct === cards.length ? copy.sortCorrect : copy.sortScore(correct, cards.length)); };
  return <LabShell title={copy.sortTitle(scenario)} eyebrow={copy.sortEyebrow} reset={copy.reset} onReset={() => { setPlacements(empty()); setResult(''); }}><p className="mb-4 text-sm text-[#516170]">{copy.sortPrompt}</p><div className="mb-5 flex min-h-16 flex-wrap gap-2 rounded-2xl border border-dashed border-[#16324f]/25 bg-white/55 p-3">{cards.filter((card) => placements[card.id] === null).map((card) => <button key={card.id} draggable onDragStart={(event) => event.dataTransfer.setData('text/plain', card.id)} onClick={() => place(card.id, 0)} className="inline-flex items-center gap-2 rounded-xl border bg-white px-3 py-2 text-xs font-semibold text-[#263b4f]"><GripVertical className="h-4 w-4 text-[#de5d3a]" />{card.label}</button>)}</div><div className="grid gap-3 md:grid-cols-3">{copy.buckets.map((bucket, index) => <div key={bucket} onDragOver={(event) => event.preventDefault()} onDrop={(event) => place(event.dataTransfer.getData('text/plain'), index)} className="min-h-36 rounded-2xl border border-[#16324f]/15 bg-[#f2eddf] p-3"><h3 className="mb-3 text-center text-xs font-bold uppercase text-[#16324f]">{bucket}</h3>{cards.filter((card) => placements[card.id] === index).map((card) => <button key={card.id} onClick={() => place(card.id, (index + 1) % copy.buckets.length)} className="mb-2 flex w-full items-center gap-2 rounded-xl bg-white px-3 py-2 text-left text-xs font-semibold text-[#263b4f]"><GripVertical className="h-4 w-4 text-[#de5d3a]" />{card.label}</button>)}</div>)}</div><div className="mt-5 flex flex-wrap items-center gap-3"><button type="button" onClick={evaluate} className="rounded-full bg-[#16324f] px-5 py-2.5 text-sm font-bold text-white">{copy.check}</button>{result && <p role="status" className="text-sm font-semibold text-[#516170]">{result}</p>}</div></LabShell>;
}

function SequenceLab({ scenario, copy }: { scenario: string; copy: Copy }) {
  const expected = copy.sequenceSteps; const initial = [expected[2], expected[0], expected[4], expected[1], expected[3]]; const [steps, setSteps] = useState(initial), [result, setResult] = useState(''); const move = (index: number, delta: number) => { const target = index + delta; if (target < 0 || target >= steps.length) return; setSteps((current) => { const next = [...current]; [next[index], next[target]] = [next[target], next[index]]; return next; }); setResult(''); }; const drop = (source: number, target: number) => { setSteps((current) => { const next = [...current]; const [item] = next.splice(source, 1); next.splice(target, 0, item); return next; }); setResult(''); };
  return <LabShell title={copy.sequenceTitle(scenario)} eyebrow={copy.sequenceEyebrow} reset={copy.reset} onReset={() => { setSteps(initial); setResult(''); }}><p className="mb-4 text-sm text-[#516170]">{copy.sequencePrompt}</p><ol className="space-y-2">{steps.map((step, index) => <li key={step} draggable onDragStart={(event) => event.dataTransfer.setData('text/plain', String(index))} onDragOver={(event) => event.preventDefault()} onDrop={(event) => drop(Number(event.dataTransfer.getData('text/plain')), index)} className="flex items-center gap-3 rounded-2xl border border-[#16324f]/15 bg-white/80 p-3"><GripVertical className="h-5 w-5 text-[#de5d3a]" /><span className="flex-grow text-sm font-semibold text-[#263b4f]">{step}</span><button aria-label={copy.moveUp(step)} disabled={index === 0} onClick={() => move(index, -1)}><ArrowUp className="h-4 w-4" /></button><button aria-label={copy.moveDown(step)} disabled={index === steps.length - 1} onClick={() => move(index, 1)}><ArrowDown className="h-4 w-4" /></button></li>)}</ol><div className="mt-5 flex gap-3"><button type="button" onClick={() => setResult(steps.every((step, index) => step === expected[index]) ? copy.sequenceCorrect : copy.sequenceWrong)} className="rounded-full bg-[#16324f] px-5 py-2.5 text-sm font-bold text-white">{copy.check}</button>{result && <p role="status" className="text-sm font-semibold text-[#516170]">{result}</p>}</div></LabShell>;
}

function CompareLab({ scenario, concepts, copy }: { scenario: string; concepts: string[]; copy: Copy }) {
  const [version, setVersion] = useState<'quick' | 'production'>('quick'), [checks, setChecks] = useState([false, false, false, false]); const score = checks.filter(Boolean).length;
  return <LabShell title={copy.compareTitle(scenario)} eyebrow={copy.compareEyebrow} reset={copy.reset} onReset={() => { setVersion('quick'); setChecks([false, false, false, false]); }}><div className="mb-5 grid grid-cols-2 rounded-full bg-[#e8e1cf] p-1 text-xs font-bold"><button onClick={() => setVersion('quick')} className={`rounded-full px-4 py-2 ${version === 'quick' ? 'bg-white text-[#de5d3a]' : 'text-[#65717c]'}`}>{copy.quick}</button><button onClick={() => setVersion('production')} className={`rounded-full px-4 py-2 ${version === 'production' ? 'bg-[#16324f] text-white' : 'text-[#65717c]'}`}>{copy.production}</button></div><div className="rounded-2xl border bg-white/75 p-5"><p className="text-sm font-bold text-[#16324f]">{version === 'quick' ? copy.quickPrompt : copy.productionPrompt(concepts)}</p><p className="mt-3 text-sm text-[#516170]">{version === 'quick' ? copy.quickBody : copy.productionBody}</p></div><p className="mb-3 mt-5 text-xs font-bold uppercase text-[#de5d3a]">{copy.criteriaPrompt}</p><div className="grid gap-2 sm:grid-cols-2">{copy.criteria.map((criterion, index) => <button key={criterion} onClick={() => setChecks((current) => current.map((value, itemIndex) => itemIndex === index ? !value : value))} className={`flex items-center gap-2 rounded-xl border px-3 py-3 text-left text-sm font-semibold ${checks[index] ? 'border-emerald-500 bg-emerald-50 text-emerald-950' : 'border-[#16324f]/15 bg-white/60 text-[#516170]'}`}><CheckCircle2 className="h-4 w-4" />{criterion}</button>)}</div><div className="mt-5 flex items-center gap-3 rounded-2xl bg-[#16324f] p-4 text-white"><Sparkles className="h-5 w-5 text-[#e6b44a]" /><p className="text-sm">{copy.compareScore(score)}</p></div></LabShell>;
}

export function InteractiveCourseware({ chapter, lesson }: Props) {
  const { i18n } = useTranslation(); const locale = (i18n.resolvedLanguage ?? i18n.language) as AppLocale; const copy = copies[locale] ?? copies.en; const concepts = useMemo(() => (lesson.skills.length ? lesson.skills : chapter.tags).slice(0, 3), [chapter.tags, lesson.skills]); const scenario = lesson.task || lesson.title.replace(/^\d{2}-\d{2}\.\s*/, '');
  if (!lesson.interaction) return null;
  if (lesson.interaction === 'slider') return <SliderLab scenario={scenario} copy={copy} />;
  if (lesson.interaction === 'sort') return <SortLab scenario={scenario} copy={copy} />;
  if (lesson.interaction === 'sequence') return <SequenceLab scenario={scenario} copy={copy} />;
  if (lesson.interaction === 'compare') return <CompareLab scenario={scenario} concepts={concepts} copy={copy} />;
  return <ChoiceLab scenario={scenario} concepts={concepts} copy={copy} />;
}
