-- Interview practice set — shared skill vocabulary.
--
-- The "AI Engineering Progressive Assessment" interview set maps every question
-- to reviewed skill nodes in the SAME `skills` table used by jobs, courses, and
-- resumes, so interview skills are immediately interchangeable with the rest of
-- the platform's knowledge graph. The 13 skills below are new; questions may
-- also reuse existing slugs such as `python-production-engineering`,
-- `ai-safety-guardrails`, `human-in-the-loop`, `model-evaluation`,
-- `agent-architecture`, and `incident-response`.
--
-- No `lesson_skill_coverage` rows are seeded here on purpose: coverage entries
-- flow into the jobs detail page, and the interview unit links from its own
-- frontend metadata until an admin explicitly approves such mappings.

INSERT INTO skills (id, slug, name_zh, name_en, definition, category, difficulty, taxonomy_version, status) VALUES ('skill_python_data_structures', 'python-data-structures', 'Python 数据结构', 'Python data structures', '熟练使用列表、字典、集合、堆与队列等内置容器，并正确处理插入顺序、唯一性与内存视图语义', 'Python 工程', 'beginner', 2, 'approved') ON CONFLICT(slug) DO UPDATE SET name_zh = excluded.name_zh, name_en = excluded.name_en, definition = excluded.definition, category = excluded.category, difficulty = excluded.difficulty, taxonomy_version = 2, status = 'approved', updated_at = CURRENT_TIMESTAMP;

INSERT INTO skills (id, slug, name_zh, name_en, definition, category, difficulty, taxonomy_version, status) VALUES ('skill_algorithm_complexity', 'algorithm-complexity', '算法与复杂度分析', 'Algorithm analysis and complexity', '用时间与空间复杂度分析选择线性扫描、排序、二分或常数空间实现，并识别最坏情况与摊销成本', 'Python 工程', 'beginner', 2, 'approved') ON CONFLICT(slug) DO UPDATE SET name_zh = excluded.name_zh, name_en = excluded.name_en, definition = excluded.definition, category = excluded.category, difficulty = excluded.difficulty, taxonomy_version = 2, status = 'approved', updated_at = CURRENT_TIMESTAMP;

INSERT INTO skills (id, slug, name_zh, name_en, definition, category, difficulty, taxonomy_version, status) VALUES ('skill_string_processing', 'string-processing', '字符串处理与匹配', 'String processing and matching', '掌握大小写归一化、子串匹配、稳定去重、前缀树（Trie）与倒排索引等字符串工程技巧', 'Python 工程', 'beginner', 2, 'approved') ON CONFLICT(slug) DO UPDATE SET name_zh = excluded.name_zh, name_en = excluded.name_en, definition = excluded.definition, category = excluded.category, difficulty = excluded.difficulty, taxonomy_version = 2, status = 'approved', updated_at = CURRENT_TIMESTAMP;

INSERT INTO skills (id, slug, name_zh, name_en, definition, category, difficulty, taxonomy_version, status) VALUES ('skill_state_machine_design', 'state-machine-design', '状态机与状态转换', 'State machine and state transitions', '用显式状态、前置条件与不变量管理对象生命周期，保证每次写操作只发生合法转换', 'Python 工程', 'intermediate', 2, 'approved') ON CONFLICT(slug) DO UPDATE SET name_zh = excluded.name_zh, name_en = excluded.name_en, definition = excluded.definition, category = excluded.category, difficulty = excluded.difficulty, taxonomy_version = 2, status = 'approved', updated_at = CURRENT_TIMESTAMP;

INSERT INTO skills (id, slug, name_zh, name_en, definition, category, difficulty, taxonomy_version, status) VALUES ('skill_sorting_aggregation', 'sorting-aggregation', '排序、聚合与统计', 'Sorting, aggregation and statistics', '实现多键复合排序、过滤、聚合与确定性的统计输出，正确处理并列与数值精度', 'Python 工程', 'beginner', 2, 'approved') ON CONFLICT(slug) DO UPDATE SET name_zh = excluded.name_zh, name_en = excluded.name_en, definition = excluded.definition, category = excluded.category, difficulty = excluded.difficulty, taxonomy_version = 2, status = 'approved', updated_at = CURRENT_TIMESTAMP;

INSERT INTO skills (id, slug, name_zh, name_en, definition, category, difficulty, taxonomy_version, status) VALUES ('skill_graph_algorithms', 'graph-algorithms', '图遍历与拓扑排序', 'Graph traversal and topological ordering', '实现 DFS/BFS、传递闭包、环检测、拓扑排序、关键路径与逆图影响分析', 'Python 工程', 'intermediate', 2, 'approved') ON CONFLICT(slug) DO UPDATE SET name_zh = excluded.name_zh, name_en = excluded.name_en, definition = excluded.definition, category = excluded.category, difficulty = excluded.difficulty, taxonomy_version = 2, status = 'approved', updated_at = CURRENT_TIMESTAMP;

INSERT INTO skills (id, slug, name_zh, name_en, definition, category, difficulty, taxonomy_version, status) VALUES ('skill_cache_design', 'cache-design', '缓存、TTL 与淘汰策略', 'Cache design, TTL and eviction', '设计 LRU/TTL 缓存，处理过期语义、惰性清理、容量上限与陈旧条目回收', 'Python 工程', 'intermediate', 2, 'approved') ON CONFLICT(slug) DO UPDATE SET name_zh = excluded.name_zh, name_en = excluded.name_en, definition = excluded.definition, category = excluded.category, difficulty = excluded.difficulty, taxonomy_version = 2, status = 'approved', updated_at = CURRENT_TIMESTAMP;

INSERT INTO skills (id, slug, name_zh, name_en, definition, category, difficulty, taxonomy_version, status) VALUES ('skill_stream_processing', 'stream-processing', '流式处理与滑动窗口', 'Stream processing and sliding windows', '实现滑动窗口、双堆在线统计、Top-K 惰性堆、水位线与迟到数据去重', 'Python 工程', 'advanced', 2, 'approved') ON CONFLICT(slug) DO UPDATE SET name_zh = excluded.name_zh, name_en = excluded.name_en, definition = excluded.definition, category = excluded.category, difficulty = excluded.difficulty, taxonomy_version = 2, status = 'approved', updated_at = CURRENT_TIMESTAMP;

INSERT INTO skills (id, slug, name_zh, name_en, definition, category, difficulty, taxonomy_version, status) VALUES ('skill_scheduling_queues', 'scheduling-queues', '调度、队列与公平性', 'Scheduling, queues and fairness', '实现优先队列、公平调度（如赤字轮转）、批量执行、区间扫描线与有界等待', 'Python 工程', 'intermediate', 2, 'approved') ON CONFLICT(slug) DO UPDATE SET name_zh = excluded.name_zh, name_en = excluded.name_en, definition = excluded.definition, category = excluded.category, difficulty = excluded.difficulty, taxonomy_version = 2, status = 'approved', updated_at = CURRENT_TIMESTAMP;

INSERT INTO skills (id, slug, name_zh, name_en, definition, category, difficulty, taxonomy_version, status) VALUES ('skill_event_sourcing', 'event-sourcing', '事件溯源与版本化存储', 'Event sourcing and versioned storage', '设计追加式事件日志、快照、历史重放、版本化读取与墓碑语义', 'Python 工程', 'advanced', 2, 'approved') ON CONFLICT(slug) DO UPDATE SET name_zh = excluded.name_zh, name_en = excluded.name_en, definition = excluded.definition, category = excluded.category, difficulty = excluded.difficulty, taxonomy_version = 2, status = 'approved', updated_at = CURRENT_TIMESTAMP;

INSERT INTO skills (id, slug, name_zh, name_en, definition, category, difficulty, taxonomy_version, status) VALUES ('skill_distributed_consensus', 'distributed-consensus', '分布式共识与仲裁', 'Distributed consensus and quorum', '实现多数派确认、连续复制日志、CRDT 合并与最终一致的复制状态', '分布式系统', 'advanced', 2, 'approved') ON CONFLICT(slug) DO UPDATE SET name_zh = excluded.name_zh, name_en = excluded.name_en, definition = excluded.definition, category = excluded.category, difficulty = excluded.difficulty, taxonomy_version = 2, status = 'approved', updated_at = CURRENT_TIMESTAMP;

INSERT INTO skills (id, slug, name_zh, name_en, definition, category, difficulty, taxonomy_version, status) VALUES ('skill_crash_recovery', 'crash-recovery', '崩溃恢复与租约', 'Crash recovery and leases', '实现租约、fencing、决策日志、幂等重试、熔断与过期 worker 拒绝', '分布式系统', 'advanced', 2, 'approved') ON CONFLICT(slug) DO UPDATE SET name_zh = excluded.name_zh, name_en = excluded.name_en, definition = excluded.definition, category = excluded.category, difficulty = excluded.difficulty, taxonomy_version = 2, status = 'approved', updated_at = CURRENT_TIMESTAMP;

INSERT INTO skills (id, slug, name_zh, name_en, definition, category, difficulty, taxonomy_version, status) VALUES ('skill_transactional_systems', 'transactional-systems', '事务与快照隔离', 'Transactions and snapshot isolation', '实现 MVCC 快照、写写冲突检测、原子批量、幂等操作与两阶段提交', '分布式系统', 'advanced', 2, 'approved') ON CONFLICT(slug) DO UPDATE SET name_zh = excluded.name_zh, name_en = excluded.name_en, definition = excluded.definition, category = excluded.category, difficulty = excluded.difficulty, taxonomy_version = 2, status = 'approved', updated_at = CURRENT_TIMESTAMP;
